[versions]
adapterRxjava3 = "2.9.0"
adapterRxjava3Version = "2.9.0"
agp = "8.9.1"
coilComposeVersion = "2.5.0"
converterGsonVersion = "2.9.0"

koinAndroid = "4.0.4"
koinAnnotation = "2.0.0"
koinCompose = "4.0.4"
koinComposeViewmodel = "4.0.4"
koinCore ="4.0.4"

kotlin = "2.0.21"
coreKtx = "1.10.1"
lifecycleRuntimeKtx = "2.6.1"
activityCompose = "1.10.1"
composeBom = "2024.09.00"
navigationCompose = "2.8.9"
kotlinSerializationJsonVersion = "1.8.0"
kotlinSerializablePlugin = "2.1.0"
retrofit = "2.9.0"
rxandroid = "3.0.2"
rxjava = "3.1.6"
kspPluginVersion = "2.1.0-1.0.29"

roomCompilerVersion = "2.7.0"

[libraries]
adapter-rxjava3 = { module = "com.squareup.retrofit2:adapter-rxjava3", version.ref = "adapterRxjava3Version" }
androidx-core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "coreKtx" }
androidx-navigation-compose = { group = "androidx.navigation", name = "navigation-compose", version.ref = "navigationCompose" }
androidx-lifecycle-runtime-ktx = { group = "androidx.lifecycle", name = "lifecycle-runtime-ktx", version.ref = "lifecycleRuntimeKtx" }
androidx-activity-compose = { group = "androidx.activity", name = "activity-compose", version.ref = "activityCompose" }
androidx-compose-bom = { group = "androidx.compose", name = "compose-bom", version.ref = "composeBom" }
androidx-ui = { group = "androidx.compose.ui", name = "ui" }
androidx-ui-graphics = { group = "androidx.compose.ui", name = "ui-graphics" }
androidx-ui-tooling-preview = { group = "androidx.compose.ui", name = "ui-tooling-preview" }
androidx-material3 = { group = "androidx.compose.material3", name = "material3" }
coil-compose = { module = "io.coil-kt:coil-compose", version.ref = "coilComposeVersion" }
converter-gson = { module = "com.squareup.retrofit2:converter-gson", version.ref = "converterGsonVersion" }
koin-android = { module = "io.insert-koin:koin-android", version.ref = "koinAndroid" }
koin-compose = { module = "io.insert-koin:koin-compose", version.ref = "koinCompose" }
koin-compose-viewmodel = { module = "io.insert-koin:koin-compose-viewmodel", version.ref = "koinComposeViewmodel" }
koin-core = { module = "io.insert-koin:koin-core", version.ref = "koinCore" }
kotlinx-serialization = { group = "org.jetbrains.kotlinx", name = "kotlinx-serialization-json", version.ref = "kotlinSerializationJsonVersion" }
retrofit = { module = "com.squareup.retrofit2:retrofit", version.ref = "retrofit" }
rxandroid = { module = "io.reactivex.rxjava3:rxandroid", version.ref = "rxandroid" }
rxjava = { module = "io.reactivex.rxjava3:rxjava", version.ref = "rxjava" }
koinAnnotation = { group = "io.insert-koin", name = "koin-annotations", version.ref = "koinAnnotation" }

room-compiler = { group = "androidx.room", name = "room-compiler", version.ref = "roomCompilerVersion" }
room-runtime = { group = "androidx.room", name = "room-runtime", version.ref = "roomCompilerVersion" }
room-rxjava3 = { group = "androidx.room", name = "room-rxjava3", version.ref = "roomCompilerVersion" }

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
kotlin-compose = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
kotlin-serializable = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlinSerializablePlugin" }
kspPlugin = { id = "com.google.devtools.ksp", version.ref = "kspPluginVersion" }
